//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebootDeleter.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RebootDeleter.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The application must be run under administrative privileges. 的本地化字符串。
        /// </summary>
        internal static string AdminPermissionRequired {
            get {
                return ResourceManager.GetString("AdminPermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete on &amp;Reboot 的本地化字符串。
        /// </summary>
        internal static string ContextMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully added to context menu. 的本地化字符串。
        /// </summary>
        internal static string ContextMenuItemAdditionSuccess {
            get {
                return ResourceManager.GetString("ContextMenuItemAdditionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The context menu item has already been removed. 的本地化字符串。
        /// </summary>
        internal static string ContextMenuItemAlreadyRemoved {
            get {
                return ResourceManager.GetString("ContextMenuItemAlreadyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully removed from context menu. 的本地化字符串。
        /// </summary>
        internal static string ContextMenuItemRemoved {
            get {
                return ResourceManager.GetString("ContextMenuItemRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to delete the following {0} file(s): 的本地化字符串。
        /// </summary>
        internal static string DeletionFailedHeader {
            get {
                return ResourceManager.GetString("DeletionFailedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully scheduled deletion for the following {0} file(s) on next reboot: 的本地化字符串。
        /// </summary>
        internal static string DeletionScheduledHeader {
            get {
                return ResourceManager.GetString("DeletionScheduledHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to add to context menu ({0}): {1} 的本地化字符串。
        /// </summary>
        internal static string ErrorContextMenuItemAddition {
            get {
                return ResourceManager.GetString("ErrorContextMenuItemAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to remove from context menu ({0}): {1} 的本地化字符串。
        /// </summary>
        internal static string ErrorContextMenuItemRemoval {
            get {
                return ResourceManager.GetString("ErrorContextMenuItemRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file does not exist 的本地化字符串。
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected error ({0}): {1} 的本地化字符串。
        /// </summary>
        internal static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose file(s) to delete 的本地化字符串。
        /// </summary>
        internal static string FileChooserTitle {
            get {
                return ResourceManager.GetString("FileChooserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
